name: dind

services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./certs:/certs/ca
      - ./var-lib-docker:/var/lib/docker:rw
      - ./data:/data:rw
    networks:
      - docker-in-docker

networks:
  docker-in-docker: {}

