name: none-network-connect

services:
  container1:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: none
    cap_add: [ "NET_ADMIN" ]

  container2:
    image: ubuntu:latest
    command: [ "sleep", "infinity" ]
    network_mode: none

